### ISSUE TITLE
Latest version not being pushed to npm // build broken

### ISSUE THREAD

**Issue by lenovouser** [primer/primer-utilities#3]
I can't pull **[`v3.7.0`](https://github.com/primer/primer-utilities/releases/tag/v3.7.0)** from the npm registry. Probably because the build is failing since commit 9b1bf79be0ad10e5a53e4388cba5fc118bd2e7f7

**/cc** @broccolini

**Comment by broccolini** [comment]
Sorry about that and apologies for the delay in reply. We missed some issues with a naming update that stopped the build states showing for each modules. That's fixed now and utilities are now passing.
